kind: Service
apiVersion: v1
metadata:
  name: pens-service
  namespace: production
spec:
  ports:
  - port: 80
    protocol: TCP
  #type: LoadBalancer
  selector:
    app: pensiun
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pens-deploy
  namespace: production
spec:
  selector:
    matchLabels:
      app: pensiun
  replicas: 2
  template:
    metadata:
      labels:
        app: pensiun
    spec:
      containers:
      - name: php-pesbuk
        image: farman17/aplikasi-pensiunmutasi
        ports:
          - containerPort: 80
       

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: pens-ingress
  namespace: production
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: pensiunan.dailybugis.my.id
    http:
      paths:
      #- path: /
      - backend:
          serviceName: pens-service
          servicePort: 80

