kind: Service
apiVersion: v1
metadata:
  name: ve-service
  namespace: production
spec:
  ports:
  - port: 80
    protocol: TCP
  #type: LoadBalancer
  selector:
    app: vet
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ve-deploy
  namespace: production
spec:
  selector:
    matchLabels:
      app: vet
  replicas: 2
  template:
    metadata:
      labels:
        app: vet
    spec:
      containers:
      - name: php-vet
        image: farman17/aplikasi-pensiunmutasi
	ports:
        - containerPort: 80
       

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ve-ingress
  namespace: production
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: pensiunan.dailybugis.my.id
    http:
      paths:
      #- path: /
      - backend:
          serviceName: ve-service
          servicePort: 80

